# Generated by Django 3.2 on 2022-04-21 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactmodel_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='tanggal_lahir',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
    ]
