# Generated by Django 3.2 on 2022-04-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220421_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='jenis_kelamin',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Laki-Laki'), ('P', 'Perempuan')], default='None', max_length=1),
        ),
    ]
