# Generated by Django 3.2 on 2022-04-12 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='yourname', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='your@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='time_post',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
