# Generated by Django 3.2 on 2022-04-21 12:27

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220417_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('blog', 'Blog'), ('jurnal', 'Jurnal')], default='blog', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[blog.validators.validate_title]),
        ),
    ]
