# Generated by Django 3.2 on 2022-04-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
